FROM alpine/git as clone
WORKDIR /app
RUN git clone https://github.com/nautilus-dev/truck-simulator.git

FROM maven:3.5-jdk-8-alpine as build
WORKDIR /app
COPY --from=clone /app/truck-simulator /app

ARG ENDPOINT
ARG TYPE
ARG PORT
ARG HOST
ARG DB
ARG COLLECTION

RUN echo "Endpoint: $ENDPOINT"
RUN echo "Type: $TYPE"
RUN echo "Port: $PORT"
RUN echo "Host: $HOST"
RUN echo "DB: $DB"
RUN echo "Collection: $COLLECTION"



RUN mvn clean package exec:java "-Dexec.args=-s $ENDPOINT -f $TYPE -p $PORT -host $HOST -db $DB -c $COLLECTION"